'use strict';

export const PLAYERS_RECEIVED = 'PLAYERS_RECEIVED';
export const PLAYER_CHANGED = 'PLAYER_CHANGED';
export const PLAYER_REMOVED = 'PLAYER_REMOVED';
export const PLAYER_ADDED = 'PLAYER_ADDED';
